# Generated by Django 5.2.5 on 2026-03-15 14:02

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_competitor_blog_post_generation_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="key",
            field=models.CharField(default=core.utils.generate_random_key, max_length=64, unique=True),
        ),
    ]
