# Generated by Django 5.2.8 on 2026-03-16 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_profile_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentExecutionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('GENERATE_BLOG_POST', 'Generate Blog Post')], max_length=64)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='QUEUED', max_length=32)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('error_message', models.TextField(blank=True, default='')),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_reason', models.TextField(blank=True, default='')),
                ('queue_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_execution_jobs', to='core.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_execution_jobs', to='core.project')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_jobs', to='core.agentexecutionjob')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'status', 'created_at'], name='core_agente_profile_26e9e0_idx'), models.Index(fields=['project', 'status', 'created_at'], name='core_agente_project_2bfd14_idx'), models.Index(fields=['operation', 'status', 'created_at'], name='core_agente_operati_d64bfa_idx')],
                'unique_together': {('profile', 'operation', 'idempotency_key')},
            },
        ),
    ]
