# Generated by Django 5.2.8 on 2026-03-16 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_agentexecutionjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkOpportunityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('SUGGESTION', 'Suggestion'), ('PLACEMENT', 'Placement')], max_length=20)),
                ('decision', models.CharField(choices=[('ALLOWED', 'Allowed'), ('BLOCKED', 'Blocked'), ('PLACED', 'Placed'), ('NOT_PLACED', 'Not Placed')], max_length=20)),
                ('candidate_url', models.URLField(max_length=500)),
                ('candidate_domain', models.CharField(blank=True, default='', max_length=255)),
                ('source_domain', models.CharField(blank=True, default='', max_length=255)),
                ('link_source', models.CharField(blank=True, default='', max_length=20)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('relevance_threshold', models.FloatField(blank=True, null=True)),
                ('proposed_anchor', models.CharField(blank=True, default='', max_length=255)),
                ('final_anchor', models.CharField(blank=True, default='', max_length=255)),
                ('relation', models.CharField(blank=True, default='', max_length=32)),
                ('policy_flags', models.JSONField(blank=True, default=list)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('candidate_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_opportunity_audit_logs', to='core.projectpage')),
                ('generated_blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_opportunity_audit_logs', to='core.generatedblogpost')),
                ('source_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_opportunity_logs_as_source', to='core.project')),
                ('target_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_opportunity_logs_as_target', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['source_project', 'phase', 'created_at'], name='core_linkop_source__b8127f_idx'), models.Index(fields=['candidate_domain', 'phase', 'created_at'], name='core_linkop_candida_a3c098_idx'), models.Index(fields=['decision', 'phase', 'created_at'], name='core_linkop_decisio_8c569a_idx')],
            },
        ),
    ]
