# Generated by Django 5.2.8 on 2026-03-16 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_linkopportunityauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedblogpost',
            name='external_links_approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], default='PENDING', max_length=32),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='external_links_review_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='external_links_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='external_links_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_external_links_blog_posts', to='core.profile'),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='publish_approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], default='PENDING', max_length=32),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='publish_review_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='publish_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedblogpost',
            name='publish_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_publish_blog_posts', to='core.profile'),
        ),
        migrations.CreateModel(
            name='BlogPostWorkflowAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('checkpoint', models.CharField(max_length=32)),
                ('event_type', models.CharField(max_length=64)),
                ('decision', models.CharField(blank=True, default='', max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post_workflow_events', to='core.profile')),
                ('generated_blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_audit_logs', to='core.generatedblogpost')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post_workflow_audit_logs', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['generated_blog_post', 'created_at'], name='core_blogpo_generat_d311a7_idx'), models.Index(fields=['project', 'checkpoint', 'created_at'], name='core_blogpo_project_74bd9e_idx'), models.Index(fields=['event_type', 'created_at'], name='core_blogpo_event_t_d0b750_idx')],
            },
        ),
    ]
