# Generated by Django 5.2.8 on 2026-03-16 16:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_generatedblogpost_external_links_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeAttributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_name', models.CharField(max_length=128)),
                ('dimension', models.CharField(choices=[('content', 'Content'), ('distribution', 'Links / Distribution'), ('technical', 'Technical Operations')], max_length=32)),
                ('outcome_metric', models.CharField(max_length=64)),
                ('outcome_value', models.FloatField(default=1.0)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_model', models.CharField(max_length=128)),
                ('source_object_id', models.BigIntegerField(blank=True, null=True)),
                ('event_fingerprint', models.CharField(max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_attribution_events', to='core.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_attribution_events', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'occurred_at'], name='core_outcom_project_2fbcf4_idx'), models.Index(fields=['project', 'dimension', 'occurred_at'], name='core_outcom_project_0d0d6c_idx'), models.Index(fields=['project', 'outcome_metric', 'occurred_at'], name='core_outcom_project_8ecbff_idx'), models.Index(fields=['event_name', 'occurred_at'], name='core_outcom_event_n_502e1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutcomeAttributionRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('window_start', models.DateField()),
                ('granularity', models.CharField(choices=[('DAY', 'Day')], default='DAY', max_length=8)),
                ('dimension', models.CharField(choices=[('content', 'Content'), ('distribution', 'Links / Distribution'), ('technical', 'Technical Operations')], max_length=32)),
                ('outcome_metric', models.CharField(max_length=64)),
                ('total_value', models.FloatField(default=0.0)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('last_aggregated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_attribution_rollups', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'window_start'], name='core_outcom_project_cf3631_idx'), models.Index(fields=['project', 'window_start', 'dimension'], name='core_outcom_project_a1a1eb_idx'), models.Index(fields=['project', 'window_start', 'outcome_metric'], name='core_outcom_project_414ee0_idx')],
                'unique_together': {('project', 'window_start', 'granularity', 'dimension', 'outcome_metric')},
            },
        ),
    ]
