# Generated by Django 5.2.8 on 2026-03-17 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_outcomeattributionevent_outcomeattributionrollup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('google_analytics', 'Google Analytics (GA4)'), ('google_search_console', 'Google Search Console'), ('plausible', 'Plausible')], max_length=64)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected')], default='disconnected', max_length=32)),
                ('external_account_email', models.EmailField(blank=True, default='', max_length=254)),
                ('scope', models.TextField(blank=True, default='')),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('plausible_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('plausible_site_id', models.CharField(blank=True, default='', max_length=255)),
                ('plausible_base_url', models.URLField(blank=True, default='https://plausible.io', max_length=255)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'provider')},
            },
        ),
    ]
