# Generated by Django 5.2.8 on 2026-03-17 14:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_projectintegration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEarnedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_page_title', models.CharField(blank=True, default='', max_length=255)),
                ('source_page_url', models.URLField(blank=True, default='', max_length=500)),
                ('target_page_url', models.URLField(max_length=500)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_anchor', models.CharField(blank=True, default='', max_length=255)),
                ('source_generated_blog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earned_links_created', to='core.generatedblogpost')),
                ('source_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_earned_links', to='core.project')),
                ('target_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earned_links_received', to='core.projectpage')),
                ('target_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_earned_links', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['target_project', 'last_seen_at'], name='core_projec_target__563404_idx'), models.Index(fields=['source_project', 'last_seen_at'], name='core_projec_source__2a2611_idx'), models.Index(fields=['target_page_url'], name='core_projec_target__d2bbd0_idx')],
                'unique_together': {('source_project', 'target_project', 'source_page_url', 'target_page_url')},
            },
        ),
    ]
