# Generated by Django 5.2.8 on 2026-03-17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_projectearnedlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSourceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("ga4", "GA4"),
                            ("gsc", "Google Search Console"),
                            ("plausible", "Plausible"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_account_ref", models.CharField(max_length=255)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("window_start_date", models.DateField()),
                ("window_end_date", models.DateField()),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("rows_count", models.IntegerField(default=0)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=32,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_source_snapshots",
                        to="core.projectintegration",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_source_snapshots",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "project",
                            "provider",
                            "window_start_date",
                            "window_end_date",
                            "-fetched_at",
                        ],
                        name="core_analyt_project_cb5745_idx",
                    ),
                    models.Index(
                        fields=["request_fingerprint"],
                        name="core_analyt_request_4f58db_idx",
                    ),
                ]
            },
        ),
        migrations.CreateModel(
            name="AnalyticsSyncCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google_analytics", "Google Analytics"),
                            ("google_search_console", "Google Search Console"),
                            ("plausible", "Plausible"),
                        ],
                        max_length=64,
                    ),
                ),
                ("source_account_ref", models.CharField(max_length=255)),
                ("last_successful_date", models.DateField(blank=True, null=True)),
                ("backfill_start_date", models.DateField(blank=True, null=True)),
                ("backfill_end_date", models.DateField(blank=True, null=True)),
                ("last_run_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_sync_cursors",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "provider", "source_account_ref"),
                        name="analytics_sync_cursor_unique_source",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="AnalyticsFactDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("ga4", "GA4"),
                            ("gsc", "Google Search Console"),
                            ("plausible", "Plausible"),
                        ],
                        max_length=32,
                    ),
                ),
                ("metric_date", models.DateField()),
                (
                    "dimension_scope",
                    models.CharField(
                        choices=[
                            ("site", "Site"),
                            ("page", "Page"),
                            ("query", "Query"),
                            ("page_query", "Page + Query"),
                            ("country", "Country"),
                            ("device", "Device"),
                            ("channel", "Channel"),
                        ],
                        max_length=32,
                    ),
                ),
                ("page_url", models.CharField(blank=True, default="", max_length=1024)),
                ("page_url_key", models.CharField(blank=True, default="", max_length=64)),
                (
                    "search_query",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "search_query_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("country_code", models.CharField(blank=True, default="", max_length=2)),
                ("device_type", models.CharField(blank=True, default="", max_length=32)),
                ("channel_group", models.CharField(blank=True, default="", max_length=64)),
                ("dimension_fingerprint", models.CharField(default="", max_length=64)),
                ("clicks", models.BigIntegerField(blank=True, null=True)),
                ("impressions", models.BigIntegerField(blank=True, null=True)),
                (
                    "ctr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "avg_position",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("sessions", models.BigIntegerField(blank=True, null=True)),
                ("users", models.BigIntegerField(blank=True, null=True)),
                ("engaged_sessions", models.BigIntegerField(blank=True, null=True)),
                (
                    "bounce_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "conversions",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("provider_payload_meta", models.JSONField(blank=True, default=dict)),
                ("ingested_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_facts_daily",
                        to="core.project",
                    ),
                ),
                (
                    "source_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="normalized_rows",
                        to="core.analyticssourcesnapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["project", "-metric_date"],
                        name="core_analyt_project_291acc_idx",
                    ),
                    models.Index(
                        fields=["project", "provider", "-metric_date"],
                        name="core_analyt_project_10445e_idx",
                    ),
                    models.Index(
                        fields=["project", "dimension_scope", "-metric_date"],
                        name="core_analyt_project_11493d_idx",
                    ),
                    models.Index(fields=["page_url_key"], name="core_analyt_page_ur_cb2d45_idx"),
                    models.Index(
                        fields=["search_query_key"],
                        name="core_analyt_search__3fce13_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "project",
                            "provider",
                            "metric_date",
                            "dimension_scope",
                            "dimension_fingerprint",
                        ),
                        name="analytics_fact_daily_unique_dimension",
                    )
                ],
            },
        ),
    ]
