# Generated by Django 5.2.8 on 2026-03-17

import django.db.models.deletion
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_analytics_ingestion_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCustomPostType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=80)),
                ("normalized_name", models.CharField(editable=False, max_length=80)),
                (
                    "prompt_guidance",
                    models.TextField(validators=[django.core.validators.MaxLengthValidator(1200)]),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_post_types",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "normalized_name"),
                        name="project_custom_post_type_unique_normalized_name",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="blogposttitlesuggestion",
            name="custom_post_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="title_suggestions",
                to="core.projectcustomposttype",
            ),
        ),
    ]
