# Generated by Django 5.2.8 on 2026-03-18 23:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_projectpage_sitemap_sync_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPageAnalysisRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("trigger", models.CharField(choices=[("manual", "Manual"), ("automatic", "Automatic")], default="manual", max_length=32)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed")], default="queued", max_length=32)),
                ("queued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("analysis_payload", models.JSONField(blank=True, default=dict)),
                ("payload_checksum", models.CharField(blank=True, default="", max_length=64)),
                ("payload_bytes", models.PositiveIntegerField(default=0)),
                ("failure_message", models.TextField(blank=True, default="")),
                ("failure_details", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_page_analysis_runs",
                        to="core.project",
                    ),
                ),
                (
                    "project_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_runs",
                        to="core.projectpage",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_page_analysis_runs",
                        to="core.profile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="projectpageanalysisrun",
            index=models.Index(fields=["project_page", "status", "created_at"], name="core_projec_project_5ca12d_idx"),
        ),
        migrations.AddIndex(
            model_name="projectpageanalysisrun",
            index=models.Index(fields=["project_page", "finished_at"], name="core_projec_project_aeb023_idx"),
        ),
        migrations.AddIndex(
            model_name="projectpageanalysisrun",
            index=models.Index(fields=["project", "created_at"], name="core_projec_project_293767_idx"),
        ),
        migrations.AddConstraint(
            model_name="projectpageanalysisrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["queued", "running"])),
                fields=("project_page",),
                name="project_page_single_active_analysis_run",
            ),
        ),
    ]
