# Generated by Django 5.2.8 on 2026-03-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_projectpageanalysisrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcustomposttype',
            name='logo',
            field=models.ImageField(blank=True, upload_to='custom_post_type_logos/'),
        ),
    ]
