"""
Django settings for tuxseo project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import logging
import os
from pathlib import Path

import environ
import logfire
import sentry_sdk
import structlog
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.integrations.openai import OpenAIIntegration
from sentry_sdk.integrations.pydantic_ai import PydanticAIIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from structlog_sentry import SentryProcessor

from tuxseo.logging_utils import scrubbing_callback
from tuxseo.posthog_logs import (
    PostHogLogsEmitter,
    PostHogLogsProcessor,
    ensure_exception_fields,
    redact_event,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(BASE_DIR / ".env")

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Options: dev, prod
ENVIRONMENT = env("ENVIRONMENT")

SENTRY_DSN = env("SENTRY_DSN", default="")

LOGFIRE_TOKEN = env("LOGFIRE_TOKEN", default="")

POSTHOG_API_KEY = env("POSTHOG_API_KEY", default="")
POSTHOG_INGEST_HOST = env("POSTHOG_INGEST_HOST", default="https://us.i.posthog.com")
POSTHOG_LOGS_ENABLED = env.bool("POSTHOG_LOGS_ENABLED", default=ENVIRONMENT == "prod")
POSTHOG_LOGS_ENDPOINT = env(
    "POSTHOG_LOGS_ENDPOINT",
    default=f"{POSTHOG_INGEST_HOST.rstrip('/')}/v1/logs",
)
POSTHOG_LOGS_BATCH_MAX_QUEUE_SIZE = env.int("POSTHOG_LOGS_BATCH_MAX_QUEUE_SIZE", default=2048)
POSTHOG_LOGS_BATCH_MAX_EXPORT_BATCH_SIZE = env.int(
    "POSTHOG_LOGS_BATCH_MAX_EXPORT_BATCH_SIZE", default=256
)
POSTHOG_LOGS_BATCH_SCHEDULE_DELAY_MILLIS = env.int(
    "POSTHOG_LOGS_BATCH_SCHEDULE_DELAY_MILLIS", default=4000
)
POSTHOG_LOGS_BATCH_EXPORT_TIMEOUT_MILLIS = env.int(
    "POSTHOG_LOGS_BATCH_EXPORT_TIMEOUT_MILLIS", default=30000
)

if LOGFIRE_TOKEN != "":
    logfire.configure(
        environment=ENVIRONMENT,
        scrubbing=logfire.ScrubbingOptions(callback=scrubbing_callback),
    )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

SITE_URL = env("SITE_URL")

# Remove the port from the SITE_URL and the https prefix (mostly for dev)
ALLOWED_HOSTS = [SITE_URL.replace("http://", "").replace("https://", "").split(":")[0]]
if DEBUG:
    ALLOWED_HOSTS.append("backend")

CSRF_TRUSTED_ORIGINS = [SITE_URL]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "django.contrib.humanize",
    "webpack_boilerplate",
    "widget_tweaks",
    "anymail",
    "djstripe",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.google",
    "django_q",
    "django_extensions",
    "django_structlog",
    "mjml",
    "core.apps.CoreConfig",
    "docs.apps.DocsConfig",
    "steering.apps.SteeringConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "tuxseo.middleware.RequestLogContextMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django_structlog.middlewares.RequestMiddleware",  # adds log for each request
]

ROOT_URLCONF = "tuxseo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            str(BASE_DIR.joinpath("frontend", "templates")),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.pro_subscription_status",
                "core.context_processors.posthog_api_key",
                "core.context_processors.available_social_providers",
                "core.context_processors.turnstile_site_key",
                "core.context_processors.referrer_banner",
            ],
        },
    },
]

WSGI_APPLICATION = "tuxseo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

POSTGRES_DB = env("POSTGRES_DB")
POSTGRES_USER = env("POSTGRES_USER")
POSTGRES_PASSWORD = env("POSTGRES_PASSWORD")
POSTGRES_HOST = env("POSTGRES_HOST")
POSTGRES_PORT = env("POSTGRES_PORT", default="5432")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": POSTGRES_DB,
        "USER": POSTGRES_USER,
        "PASSWORD": POSTGRES_PASSWORD,
        "HOST": POSTGRES_HOST,
        "PORT": POSTGRES_PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR.joinpath("static/")

STATICFILES_DIRS = [
    BASE_DIR.joinpath("frontend/build"),
]


folder_name = f"tuxseo-{ENVIRONMENT}"
aws_s3_endpoint_url = env("AWS_S3_ENDPOINT_URL", default="")

MEDIA_URL = f"{aws_s3_endpoint_url}/{folder_name}/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

if not aws_s3_endpoint_url:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": MEDIA_ROOT,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "bucket_name": folder_name,
                "default_acl": "public-read",
                "region_name": "eu-east-1",
                "endpoint_url": aws_s3_endpoint_url,
                "access_key": env("AWS_ACCESS_KEY_ID"),
                "secret_key": env("AWS_SECRET_ACCESS_KEY"),
                "querystring_auth": False,
                "file_overwrite": False,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

WEBPACK_LOADER = {
    "MANIFEST_FILE": BASE_DIR.joinpath("frontend/build/manifest.json"),
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
SITE_ID = 1

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

if ENVIRONMENT != "dev":
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"


LOGIN_REDIRECT_URL = "home"
ACCOUNT_LOGOUT_REDIRECT_URL = "landing"

ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ALLOW_SIGNUPS = env.bool("ALLOW_SIGNUPS", default=True)
ACCOUNT_ADAPTER = "core.adapters.CustomAccountAdapter"
ACCOUNT_FORMS = {
    "signup": "core.forms.CustomSignUpForm",
    "login": "core.forms.CustomLoginForm",
}
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""
ACCOUNT_EMAIL_UNKNOWN_ACCOUNTS = False

SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_ADAPTER = "core.adapters.CustomSocialAccountAdapter"
SOCIALACCOUNT_PROVIDERS = {}

GITHUB_CLIENT_ID = env("GITHUB_CLIENT_ID", default="")
if GITHUB_CLIENT_ID != "":
    SOCIALACCOUNT_PROVIDERS["github"] = {
        "VERIFIED_EMAIL": True,
        "EMAIL_AUTHENTICATION": True,
        "AUTO_SIGNUP": True,
        "APP": {
            "client_id": env("GITHUB_CLIENT_ID"),
            "secret": env("GITHUB_CLIENT_SECRET"),
        },
    }

GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET", default="")
if GOOGLE_CLIENT_ID != "":
    SOCIALACCOUNT_PROVIDERS["google"] = {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "OAUTH_PKCE_ENABLED": True,
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID"),
            "secret": env("GOOGLE_CLIENT_SECRET"),
        },
        "AUTO_SIGNUP": True,
        "EMAIL_AUTHENTICATION": True,
    }

MAILGUN_API_KEY = env("MAILGUN_API_KEY", default="")
ANYMAIL = {
    "MAILGUN_API_KEY": MAILGUN_API_KEY,
    "MAILGUN_SENDER_DOMAIN": "mg.tuxseo.com",
}
DEFAULT_FROM_EMAIL = "Rasul from TuxSEO <rasul@tuxseo.com>"
SERVER_EMAIL = "TuxSEO Errors <error@tuxseo.com>"

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "mailhog"  # Use the service name from docker-compose
    EMAIL_PORT = 1025
    EMAIL_USE_TLS = False
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""
else:
    if MAILGUN_API_KEY == "":
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    else:
        EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"

REDIS_HOST = env("REDIS_HOST", default="localhost")
REDIS_PORT = env("REDIS_PORT", default="6379")
REDIS_PASSWORD = env("REDIS_PASSWORD", default="")
REDIS_DB = env("REDIS_DB", default="0")
REDIS_URL = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

USE_REDIS_CACHE = env.bool("USE_REDIS_CACHE", default=ENVIRONMENT != "dev")

if USE_REDIS_CACHE:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "tuxseo-local-cache",
        }
    }

Q_CLUSTER = {
    "name": "tuxseo-q",
    "timeout": 3600,  # 1 hour
    "retry": 4800,  # 80 minutes
    "workers": 4,
    "max_attempts": 2,
    "redis": REDIS_URL,
    "error_reporter": {},
}

SITEMAP_SYNC_INTERVAL_HOURS = max(1, env.int("SITEMAP_SYNC_INTERVAL_HOURS", default=6))
SITEMAP_SYNC_SCHEDULER_ENABLED = env.bool("SITEMAP_SYNC_SCHEDULER_ENABLED", default=True)
SITEMAP_SYNC_TIMEOUT_SECONDS = max(5, env.int("SITEMAP_SYNC_TIMEOUT_SECONDS", default=30))
SITEMAP_SYNC_MAX_RETRIES = max(1, env.int("SITEMAP_SYNC_MAX_RETRIES", default=3))
SITEMAP_SYNC_RETRY_BACKOFF_SECONDS = max(
    0.1, env.float("SITEMAP_SYNC_RETRY_BACKOFF_SECONDS", default=1.0)
)
SITEMAP_SYNC_MAX_INDEX_DEPTH = max(0, env.int("SITEMAP_SYNC_MAX_INDEX_DEPTH", default=2))
SITEMAP_SYNC_MAX_CHILD_SITEMAPS = max(1, env.int("SITEMAP_SYNC_MAX_CHILD_SITEMAPS", default=50))
SITEMAP_SYNC_LOCK_TTL_SECONDS = max(60, env.int("SITEMAP_SYNC_LOCK_TTL_SECONDS", default=3600))


def extract_from_record(logger, name, event_dict):
    """
    Extract thread name and add them to the event dict.
    """
    record = event_dict["_record"]
    event_dict["thread_id"] = record.thread
    return event_dict


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(levelname)s %(message)s"},
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
        },
        "json": {"format": "%(message)s"},
        "json_formatter": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processors": [
                extract_from_record,
                structlog.stdlib.ProcessorFormatter.remove_processors_meta,
                structlog.processors.JSONRenderer(),
            ],
        },
        "plain_console": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(),
        },
        "key_value": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.processors.KeyValueRenderer(
                key_order=["timestamp", "level", "event", "logger"]
            ),
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "plain_console",
            "level": "DEBUG",
        },
        "prod_console": {
            "class": "logging.StreamHandler",
            "formatter": "plain_console",
            "level": "DEBUG",
        },
        "json_console": {
            "class": "logging.StreamHandler",
            "formatter": "json_formatter",
            "level": "DEBUG",
        },
    },
    "loggers": {
        "django_structlog": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
        # django.server can log some low-level logs, but also does log requests,
        # for some reason...
        "django.server": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",  # so we don't chunder 404s, etc
            "propagate": False,
        },
        "tuxseo": {
            "level": "DEBUG",
            "handlers": ["console"],
            "propagate": False,
        },
    },
}

posthog_logs_emitter = PostHogLogsEmitter(
    enabled=POSTHOG_LOGS_ENABLED,
    endpoint=POSTHOG_LOGS_ENDPOINT,
    api_key=POSTHOG_API_KEY,
    service_name="tuxseo-backend",
    environment=ENVIRONMENT,
    batch_max_queue_size=POSTHOG_LOGS_BATCH_MAX_QUEUE_SIZE,
    batch_max_export_batch_size=POSTHOG_LOGS_BATCH_MAX_EXPORT_BATCH_SIZE,
    batch_schedule_delay_millis=POSTHOG_LOGS_BATCH_SCHEDULE_DELAY_MILLIS,
    batch_export_timeout_millis=POSTHOG_LOGS_BATCH_EXPORT_TIMEOUT_MILLIS,
)

structlog_processors = [
    structlog.contextvars.merge_contextvars,
    structlog.stdlib.filter_by_level,
    structlog.processors.TimeStamper(fmt="iso"),
    structlog.stdlib.add_logger_name,
    structlog.stdlib.add_log_level,
    structlog.stdlib.PositionalArgumentsFormatter(),
    structlog.processors.StackInfoRenderer(),
    structlog.processors.format_exc_info,
    ensure_exception_fields,
    redact_event,
]

if posthog_logs_emitter.enabled:
    structlog_processors.append(PostHogLogsProcessor(posthog_logs_emitter))

if SENTRY_DSN:
    structlog_processors.append(
        SentryProcessor(
            event_level=logging.ERROR,
            level=logging.INFO,
            active=True,
            as_context=True,
            tag_keys="__all__",
            verbose=True,
        )
    )

if LOGFIRE_TOKEN:
    structlog_processors.append(logfire.StructlogProcessor())

structlog_processors.extend(
    [
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ]
)

structlog.configure(
    processors=structlog_processors,
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)

if ENVIRONMENT == "prod":
    LOGGING["loggers"]["django.server"]["level"] = "WARNING"
    LOGGING["loggers"]["django_structlog"]["handlers"].append("json_console")
    LOGGING["loggers"]["tuxseo"]["level"] = env("DJANGO_LOG_LEVEL", default="INFO")
    LOGGING["loggers"]["tuxseo"]["handlers"].append("json_console")

if SENTRY_DSN and ENVIRONMENT == "prod":
    Q_CLUSTER["error_reporter"]["sentry"] = {"dsn": SENTRY_DSN}
    sentry_sdk.init(
        debug=DEBUG,
        dsn=SENTRY_DSN,
        environment=ENVIRONMENT,
        send_default_pii=True,
        traces_sample_rate=1,
        profile_session_sample_rate=1,
        profile_lifecycle="trace",
        integrations=[
            DjangoIntegration(),
            RedisIntegration(),
            PydanticAIIntegration(),
        ],
        disabled_integrations=[LoggingIntegration(), OpenAIIntegration()],
        attach_stacktrace=True,
        include_local_variables=True,
    )

BUTTONDOWN_API_KEY = env("BUTTONDOWN_API_KEY", default="")

TWENTY_CRM_BASE_URL = env("TWENTY_CRM_BASE_URL", default="")
TWENTY_CRM_API_KEY = env(
    "TWENTY_CRM_API_KEY",
    default=env("TWENTY_TUXSEO_API_KEY", default=env("TWENTY_API_KEY", default="")),
)
TWENTY_SIGNUP_SYNC_ENABLED = env.bool("TWENTY_SIGNUP_SYNC_ENABLED", default=False)
TWENTY_SIGNUP_SYNC_TIMEOUT_SECONDS = env.int("TWENTY_SIGNUP_SYNC_TIMEOUT_SECONDS", default=20)
TWENTY_SIGNUP_SYNC_MAX_RETRIES = env.int("TWENTY_SIGNUP_SYNC_MAX_RETRIES", default=3)

STRIPE_LIVE_SECRET_KEY = env("STRIPE_LIVE_SECRET_KEY", default="")
STRIPE_TEST_SECRET_KEY = env("STRIPE_TEST_SECRET_KEY", default="")
STRIPE_PRICE_ID_PRO_MONTHLY = env("STRIPE_PRICE_ID_PRO_MONTHLY", default="")
STRIPE_PRICE_ID_PRO_YEARLY = env("STRIPE_PRICE_ID_PRO_YEARLY", default="")

STRIPE_LIVE_MODE = False
STRIPE_SECRET_KEY = STRIPE_TEST_SECRET_KEY
if ENVIRONMENT == "prod":
    STRIPE_LIVE_MODE = True
    STRIPE_SECRET_KEY = STRIPE_LIVE_SECRET_KEY

DJSTRIPE_WEBHOOK_SECRET = env("DJSTRIPE_WEBHOOK_SECRET", default="")
DJSTRIPE_FOREIGN_KEY_TO_FIELD = "id"

JINA_READER_API_KEY = env("JINA_READER_API_KEY")

GEMINI_API_KEY = env("GEMINI_API_KEY")
PERPLEXITY_API_KEY = env("PERPLEXITY_API_KEY")

KEYWORDS_EVERYWHERE_API_KEY = env("KEYWORDS_EVERYWHERE_API_KEY")
EXA_API_KEY = env("EXA_API_KEY", default="")
BACKLINK_PROSPECTS_CONFIG = {
    "ENRICH_FETCH_TIMEOUT_SECONDS": max(
        1,
        env.int("BACKLINK_PROSPECTS_ENRICH_FETCH_TIMEOUT_SECONDS", default=5),
    ),
    "ENRICH_TOTAL_BUDGET_SECONDS": max(
        1,
        env.int("BACKLINK_PROSPECTS_ENRICH_TOTAL_BUDGET_SECONDS", default=20),
    ),
    "EXA_REQUEST_TIMEOUT_SECONDS": max(
        2,
        env.int("BACKLINK_PROSPECTS_EXA_REQUEST_TIMEOUT_SECONDS", default=20),
    ),
    "PROVIDER_MAX_RETRIES": max(
        0,
        env.int("BACKLINK_PROSPECTS_PROVIDER_MAX_RETRIES", default=2),
    ),
    "PROVIDER_RETRY_BACKOFF_SECONDS": max(
        0,
        env.float("BACKLINK_PROSPECTS_PROVIDER_RETRY_BACKOFF_SECONDS", default=0.75),
    ),
    "PROVIDER_RETRY_BACKOFF_MAX_SECONDS": max(
        1,
        env.float("BACKLINK_PROSPECTS_PROVIDER_RETRY_BACKOFF_MAX_SECONDS", default=8.0),
    ),
}
EXTERNAL_AUTHORITY_LINK_TARGET = max(
    1,
    min(3, env.int("EXTERNAL_AUTHORITY_LINK_TARGET", default=2)),
)

# GPT-Researcher Configuration
OPENAI_API_KEY = env("OPENAI_API_KEY", default="")
TAVILY_API_KEY = env("TAVILY_API_KEY", default="")

MJML_BACKEND_MODE = "httpserver"
MJML_URL = env("MJML_URL", default="")
MJML_HTTPSERVERS = [
    {
        "URL": f"{MJML_URL}/v1/render",
    }
]

CLOUDFLARE_TURNSTILE_SITEKEY = env("CLOUDFLARE_TURNSTILE_SITEKEY", default="")
CLOUDFLARE_TURNSTILE_SECRET_KEY = env("CLOUDFLARE_TURNSTILE_SECRET_KEY", default="")

REQUIRE_VERIFIED_EMAIL_FOR_EXPENSIVE_ACTIONS = env.bool(
    "REQUIRE_VERIFIED_EMAIL_FOR_EXPENSIVE_ACTIONS", default=True
)

# Detail View paid feature controls
DETAIL_VIEW_SEO_ANALYSIS_ENABLED = env.bool("DETAIL_VIEW_SEO_ANALYSIS_ENABLED", default=True)
DETAIL_VIEW_BACKLINK_DISCOVERY_ENABLED = env.bool(
    "DETAIL_VIEW_BACKLINK_DISCOVERY_ENABLED", default=True
)
DETAIL_VIEW_CONTACT_ENRICHMENT_ENABLED = env.bool(
    "DETAIL_VIEW_CONTACT_ENRICHMENT_ENABLED", default=True
)
DETAIL_VIEW_SEO_ANALYSIS_DAILY_LIMIT = env.int("DETAIL_VIEW_SEO_ANALYSIS_DAILY_LIMIT", default=20)
DETAIL_VIEW_BACKLINK_DISCOVERY_DAILY_LIMIT = env.int(
    "DETAIL_VIEW_BACKLINK_DISCOVERY_DAILY_LIMIT", default=12
)
DETAIL_VIEW_BACKLINK_DISCOVERY_COOLDOWN_SECONDS = env.int(
    "DETAIL_VIEW_BACKLINK_DISCOVERY_COOLDOWN_SECONDS", default=45
)
DETAIL_VIEW_ACTION_RATE_LIMIT_ATTEMPTS = env.int(
    "DETAIL_VIEW_ACTION_RATE_LIMIT_ATTEMPTS", default=6
)
DETAIL_VIEW_ACTION_RATE_LIMIT_WINDOW_SECONDS = env.int(
    "DETAIL_VIEW_ACTION_RATE_LIMIT_WINDOW_SECONDS", default=60
)

SIGNUP_RATE_LIMIT_ATTEMPTS_PER_IP = env.int("SIGNUP_RATE_LIMIT_ATTEMPTS_PER_IP", default=8)
SIGNUP_RATE_LIMIT_WINDOW_SECONDS = env.int("SIGNUP_RATE_LIMIT_WINDOW_SECONDS", default=3600)
SIGNUP_DISPOSABLE_EMAIL_DOMAIN_BLOCKLIST = env.list(
    "SIGNUP_DISPOSABLE_EMAIL_DOMAIN_BLOCKLIST",
    default=[
        "10minutemail.com",
        "guerrillamail.com",
        "mailinator.com",
        "temp-mail.org",
        "tempmail.com",
        "yopmail.com",
    ],
)

REPLICATE_API_TOKEN = env("REPLICATE_API_TOKEN", default="")

SHELL_PLUS_IMPORTS = [
    "from django_q.tasks import async_task",
    "from core.scheduled_tasks import *",
    "from core.tasks import *",
]
